// <auto-generated />
using System;
using CommunityWorkshopOrganizer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CommunityWorkshopOrganizer.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20260420104600_AddWorkshopStatus")]
    partial class AddWorkshopStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("CommunityWorkshopOrganizer.Models.Registration", b =>
                {
                    b.Property<int>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WorkshopId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RegistrationId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkshopId");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("CommunityWorkshopOrganizer.Models.Resource", b =>
                {
                    b.Property<int>("ResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResourceUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WorkshopId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ResourceId");

                    b.HasIndex("WorkshopId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("CommunityWorkshopOrganizer.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CommunityWorkshopOrganizer.Models.Workshop", b =>
                {
                    b.Property<int>("WorkshopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrganizerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpeakerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("WorkshopId");

                    b.HasIndex("OrganizerId");

                    b.ToTable("Workshops");
                });

            modelBuilder.Entity("CommunityWorkshopOrganizer.Models.Registration", b =>
                {
                    b.HasOne("CommunityWorkshopOrganizer.Models.User", "User")
                        .WithMany("Registrations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CommunityWorkshopOrganizer.Models.Workshop", "Workshop")
                        .WithMany("Registrations")
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("CommunityWorkshopOrganizer.Models.Resource", b =>
                {
                    b.HasOne("CommunityWorkshopOrganizer.Models.Workshop", "Workshop")
                        .WithMany("Resources")
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("CommunityWorkshopOrganizer.Models.Workshop", b =>
                {
                    b.HasOne("CommunityWorkshopOrganizer.Models.User", "Organizer")
                        .WithMany("Workshops")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("CommunityWorkshopOrganizer.Models.User", b =>
                {
                    b.Navigation("Registrations");

                    b.Navigation("Workshops");
                });

            modelBuilder.Entity("CommunityWorkshopOrganizer.Models.Workshop", b =>
                {
                    b.Navigation("Registrations");

                    b.Navigation("Resources");
                });
#pragma warning restore 612, 618
        }
    }
}
