/* ━━━ REALISTIC MOCK DATA ━━━ */

export const MOCK_WORKSHOPS = [
  {
    id: 1,
    title: 'Building Accessible React Components',
    description: 'Learn how to build inclusive, accessible UIs with React. We\'ll cover ARIA attributes, keyboard navigation, screen reader testing, and common patterns for accessible forms, modals, and dropdown menus.',
    date: '2026-05-15T10:00:00',
    location: 'Room 204, Innovation Hub',
    speaker: 'Sarah Chen',
    capacity: 30,
    currentAttendees: 24,
    category: 'React',
    tags: ['React', 'CSS', 'Design'],
    status: 'Approved',
    organizerId: 2,
    organizerName: 'Sarah Chen',
  },
  {
    id: 2,
    title: 'Docker & Kubernetes in Production',
    description: 'A deep-dive into container orchestration. Set up multi-container apps, configure health checks, manage secrets, and deploy to a Kubernetes cluster with zero-downtime rolling updates.',
    date: '2026-05-18T14:00:00',
    location: 'Conference Hall B',
    speaker: 'Marcus Johnson',
    capacity: 40,
    currentAttendees: 40,
    category: 'DevOps',
    tags: ['DevOps', 'Docker', 'Cloud'],
    status: 'Approved',
    organizerId: 3,
    organizerName: 'Marcus Johnson',
  },
  {
    id: 3,
    title: 'Advanced CSS Grid Techniques',
    description: 'Go beyond the basics. Master subgrid, named grid areas, responsive layouts without media queries, and creative grid animations that push the boundaries of what CSS can do.',
    date: '2026-05-22T11:00:00',
    location: 'Design Lab, 3rd Floor',
    speaker: 'Priya Patel',
    capacity: 25,
    currentAttendees: 12,
    category: 'CSS',
    tags: ['CSS', 'Design'],
    status: 'Approved',
    organizerId: 4,
    organizerName: 'Priya Patel',
  },
  {
    id: 4,
    title: 'TypeScript for Backend Developers',
    description: 'Bridge the gap between frontend and backend TypeScript. Learn about type-safe APIs, Zod validation schemas, tRPC, and how to share types across your entire stack.',
    date: '2026-05-25T09:30:00',
    location: 'Virtual — Zoom',
    speaker: 'Alex Rivera',
    capacity: 50,
    currentAttendees: 35,
    category: 'TypeScript',
    tags: ['TypeScript', 'Node.js'],
    status: 'Approved',
    organizerId: 5,
    organizerName: 'Alex Rivera',
  },
  {
    id: 5,
    title: 'Intro to Machine Learning with Python',
    description: 'Your first step into ML. We\'ll build a sentiment analysis model from scratch using scikit-learn, explore data preprocessing pipelines, and evaluate model performance.',
    date: '2026-05-28T15:00:00',
    location: 'AI Research Lab',
    speaker: 'Dr. Lena Kowalski',
    capacity: 20,
    currentAttendees: 18,
    category: 'AI/ML',
    tags: ['Python', 'AI/ML'],
    status: 'Pending',
    organizerId: 6,
    organizerName: 'Dr. Lena Kowalski',
  },
  {
    id: 6,
    title: 'GraphQL API Design Patterns',
    description: 'Design scalable GraphQL APIs. Cover schema-first design, pagination strategies, N+1 query prevention, authentication middleware, and real-time subscriptions.',
    date: '2026-06-02T13:00:00',
    location: 'Room 110, Tech Center',
    speaker: 'James Wright',
    capacity: 35,
    currentAttendees: 8,
    category: 'GraphQL',
    tags: ['GraphQL', 'Node.js'],
    status: 'Pending',
    organizerId: 7,
    organizerName: 'James Wright',
  },
  {
    id: 7,
    title: 'Security Best Practices for Web Apps',
    description: 'Protect your applications from the top OWASP vulnerabilities. Hands-on lab covering XSS prevention, CSRF tokens, Content Security Policy, and secure authentication flows.',
    date: '2026-06-05T10:00:00',
    location: 'Security Ops Room',
    speaker: 'Nina Okafor',
    capacity: 30,
    currentAttendees: 22,
    category: 'Security',
    tags: ['Security', 'Node.js'],
    status: 'Approved',
    organizerId: 8,
    organizerName: 'Nina Okafor',
  },
  {
    id: 8,
    title: 'React Native: Cross-Platform Mobile Apps',
    description: 'Build a production-ready mobile app with React Native and Expo. Learn navigation, native modules, push notifications, and app store deployment strategies.',
    date: '2026-06-10T11:00:00',
    location: 'Mobile Dev Lab',
    speaker: 'Tom Garcia',
    capacity: 25,
    currentAttendees: 25,
    category: 'Mobile',
    tags: ['React', 'Mobile'],
    status: 'Rejected',
    organizerId: 9,
    organizerName: 'Tom Garcia',
  },
  {
    id: 9,
    title: 'Cloud Architecture with AWS',
    description: 'Design resilient cloud architectures. We\'ll walk through serverless patterns, event-driven microservices, infrastructure as code with CDK, and cost optimization strategies.',
    date: '2026-06-14T09:00:00',
    location: 'Virtual — Google Meet',
    speaker: 'Amara Williams',
    capacity: 60,
    currentAttendees: 42,
    category: 'Cloud',
    tags: ['Cloud', 'DevOps'],
    status: 'Approved',
    organizerId: 10,
    organizerName: 'Amara Williams',
  },
];

export const MOCK_REGISTRATIONS = [
  { id: 1, workshopId: 1, userId: 1, registeredAt: '2026-04-10T08:30:00', status: 'Confirmed' },
  { id: 2, workshopId: 3, userId: 1, registeredAt: '2026-04-12T14:20:00', status: 'Confirmed' },
  { id: 3, workshopId: 7, userId: 1, registeredAt: '2026-04-15T09:00:00', status: 'Confirmed' },
];

export const MOCK_USERS = [
  { id: 1, fullName: 'Demo User', email: 'demo@example.com', role: 'Attendee', joinedAt: '2026-01-15', status: 'Active' },
  { id: 2, fullName: 'Sarah Chen', email: 'sarah.chen@example.com', role: 'Organizer', joinedAt: '2026-01-20', status: 'Active' },
  { id: 3, fullName: 'Marcus Johnson', email: 'marcus.j@example.com', role: 'Organizer', joinedAt: '2026-02-01', status: 'Active' },
  { id: 4, fullName: 'Priya Patel', email: 'priya.p@example.com', role: 'Organizer', joinedAt: '2026-02-10', status: 'Active' },
  { id: 5, fullName: 'Alex Rivera', email: 'alex.r@example.com', role: 'Organizer', joinedAt: '2026-02-15', status: 'Active' },
  { id: 6, fullName: 'Dr. Lena Kowalski', email: 'lena.k@example.com', role: 'Organizer', joinedAt: '2026-03-01', status: 'Active' },
  { id: 7, fullName: 'James Wright', email: 'james.w@example.com', role: 'Organizer', joinedAt: '2026-03-05', status: 'Active' },
  { id: 8, fullName: 'Nina Okafor', email: 'nina.o@example.com', role: 'Organizer', joinedAt: '2026-03-10', status: 'Suspended' },
  { id: 9, fullName: 'Tom Garcia', email: 'tom.g@example.com', role: 'Attendee', joinedAt: '2026-03-12', status: 'Active' },
  { id: 10, fullName: 'Amara Williams', email: 'amara.w@example.com', role: 'Organizer', joinedAt: '2026-03-18', status: 'Active' },
  { id: 11, fullName: 'Jordan Kim', email: 'jordan.k@example.com', role: 'Attendee', joinedAt: '2026-03-20', status: 'Active' },
  { id: 12, fullName: 'Emma Taylor', email: 'emma.t@example.com', role: 'Manager', joinedAt: '2026-01-01', status: 'Active' },
];

export const MOCK_ATTENDEES = [
  { registrationId: 1, user: { fullName: 'Jordan Kim', email: 'jordan.k@example.com' }, registeredAt: '2026-04-10T08:30:00', status: 'Confirmed' },
  { registrationId: 2, user: { fullName: 'Emma Taylor', email: 'emma.t@example.com' }, registeredAt: '2026-04-11T09:15:00', status: 'Confirmed' },
  { registrationId: 3, user: { fullName: 'Tom Garcia', email: 'tom.g@example.com' }, registeredAt: '2026-04-12T14:20:00', status: 'Confirmed' },
  { registrationId: 4, user: { fullName: 'Demo User', email: 'demo@example.com' }, registeredAt: '2026-04-13T11:00:00', status: 'Confirmed' },
  { registrationId: 5, user: { fullName: 'Aisha Mohammed', email: 'aisha.m@example.com' }, registeredAt: '2026-04-14T16:45:00', status: 'Waitlisted' },
];

export const MOCK_NOTIFICATIONS = [
  { id: 1, type: 'rsvp', title: 'Spot saved! See you there 🎉', message: 'You\'re registered for "Building Accessible React Components" on May 15.', time: '2 hours ago', read: false },
  { id: 2, type: 'reminder', title: 'Workshop tomorrow!', message: '"Advanced CSS Grid Techniques" starts tomorrow at 11:00 AM in Design Lab.', time: '5 hours ago', read: false },
  { id: 3, type: 'waitlist', title: 'Good news! A spot opened up', message: 'You\'ve been moved off the waitlist for "Docker & Kubernetes in Production".', time: '1 day ago', read: true },
  { id: 4, type: 'update', title: 'Location changed', message: '"TypeScript for Backend Developers" has moved to Virtual — Zoom.', time: '2 days ago', read: true },
  { id: 5, type: 'rsvp', title: 'Spot saved!', message: 'You\'re all set for "Security Best Practices for Web Apps" on June 5.', time: '3 days ago', read: true },
];

export const MOCK_ACTIVITY = [
  { id: 1, action: 'Sarah Chen submitted "Building Accessible React Components" for review', time: '3 hours ago' },
  { id: 2, action: 'Marcus Johnson\'s "Docker & Kubernetes" reached full capacity', time: '5 hours ago' },
  { id: 3, action: 'New user Jordan Kim registered as Attendee', time: '1 day ago' },
  { id: 4, action: 'Workshop "GraphQL API Design Patterns" submitted for review', time: '1 day ago' },
  { id: 5, action: 'Tom Garcia\'s "React Native" workshop was rejected — needs more detail', time: '2 days ago' },
  { id: 6, action: '"Cloud Architecture with AWS" approved by Manager', time: '2 days ago' },
];
